---
permalink: deploy/concept_configure_your_storage_system_environment.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP per VMware vSphere offrono un unico meccanismo per rilevare i sistemi storage e impostare le credenziali dello storage. Le credenziali forniscono le autorizzazioni ONTAP necessarie per consentire agli utenti dei tool ONTAP di eseguire le attività utilizzando i sistemi storage. 
---
= Configurare i tool ONTAP per il sistema storage VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP® per VMware vSphere offrono un unico meccanismo per rilevare i sistemi storage e impostare le credenziali dello storage. Le credenziali forniscono le autorizzazioni ONTAP necessarie per consentire agli utenti dei tool ONTAP di eseguire le attività utilizzando i sistemi storage.

Prima che i tool ONTAP possano visualizzare e gestire le risorse storage, i tool ONTAP devono rilevare i sistemi storage. Nell'ambito del processo di rilevamento, è necessario fornire le credenziali ONTAP per i sistemi storage. Si tratta dei privilegi (o ruoli) associati alla coppia di nome utente e password assegnata a ciascun sistema di storage. Queste coppie di nome utente e password utilizzano il RBAC (Role-Based Access Control) di ONTAP e devono essere configurate da ONTAP. Non è possibile modificare queste credenziali dall'interno degli strumenti ONTAP. È possibile definire i ruoli RBAC di ONTAP utilizzando Gestore di sistema di ONTAP.


NOTE: Se si effettua l'accesso come amministratore, si dispone automaticamente di tutti i privilegi per il sistema di storage in questione.

Quando si aggiunge un sistema storage agli strumenti ONTAP, è necessario fornire un indirizzo IP per il sistema di storage e la coppia di nome utente e password associati a tale sistema. È possibile impostare le credenziali predefinite che i tool ONTAP utilizzeranno durante il processo di rilevamento del sistema storage oppure è possibile inserire manualmente le credenziali quando viene rilevato il sistema storage. I dettagli del sistema storage aggiunto agli strumenti ONTAP vengono automaticamente inviati alle estensioni abilitate nell'implementazione. Non è necessario aggiungere manualmente lo storage al provider VASA e a Storage Replication Adapter (SRA). Sia i tool ONTAP che SRA supportano l'aggiunta di credenziali a livello di cluster e a livello di Storage Virtual Machine (SVM). IL provider VASA supporta solo le credenziali a livello di cluster per l'aggiunta di sistemi storage. Quando si aggiunge un sistema storage, qualsiasi comunicazione tra il plug-in degli strumenti ONTAP e il sistema storage deve essere autenticata reciprocamente.

Se il tuo ambiente include più istanze di vCenter Server, quando Aggiungi un sistema storage agli strumenti ONTAP dalla pagina sistemi storage, la finestra di dialogo Add Storage System (Aggiungi sistema storage) visualizza una finestra di dialogo vCenter Server in cui è possibile specificare a quale istanza di vCenter Server deve essere aggiunto il sistema storage. Se si aggiunge un sistema storage facendo clic con il pulsante destro del mouse sul nome di un data center, non è possibile specificare un'istanza di vCenter Server perché il server è già associato a tale data center.

Il rilevamento avviene in uno dei seguenti modi. In ogni caso, è necessario fornire le credenziali per qualsiasi sistema storage appena rilevato.

* All'avvio del servizio Strumenti ONTAP, gli strumenti ONTAP avviano il processo di ricerca automatico in background.
* È possibile fare clic sul pulsante *RISCOPRI tutto* nella pagina sistemi storage o su un host o un data center per selezionarlo dal menu *azioni* (*azioni* > *NetApp ONTAP Tools* > *Aggiorna dati host e storage*). È inoltre possibile fare clic su *DISCOVER* nella scheda Getting Started (Guida introduttiva) della sezione Overview (Panoramica).


Tutte le funzionalità degli strumenti di ONTAP richiedono autorizzazioni specifiche per l'esecuzione delle attività. È possibile limitare le operazioni che gli utenti possono eseguire in base alle credenziali associate al ruolo di ONTAP. Tutti gli utenti che hanno la stessa coppia di nome utente e password del sistema di storage condividono lo stesso set di credenziali del sistema di storage e possono eseguire le stesse operazioni.
