---
permalink: deploy/concept_how_to_download_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: È possibile scaricare il file .ova per i tool ONTAP per VMware vSphere dal sito del supporto NetApp. 
---
= Come scaricare gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile scaricare `.zip` File contenente file binari (_.ova_) e certificati firmati per i tool ONTAP per VMware vSphere di https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^].

Il file _.ova_ include gli strumenti ONTAP. Una volta completata la distribuzione, gli strumenti ONTAP, i prodotti VASA e SRA vengono installati nel proprio ambiente. Per impostazione predefinita, gli strumenti ONTAP iniziano a funzionare non appena si decide in merito al modello di distribuzione successivo e si sceglie se abilitare il provider VASA e SRA in base ai propri requisiti.

Se si desidera attivare SRA nella distribuzione degli strumenti ONTAP, è necessario aver installato il plug-in SRA sul server SRM (Site Recovery Manager). È possibile scaricare il file di installazione per il plug-in SRA dal menu *Storage Replication Adapter for ONTAP* nella sezione Download del software.
