---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: Per impostazione predefinita, i tool di ONTAP utilizzano porte designate per consentire la comunicazione tra i suoi componenti, che comprendono i sistemi storage e VMware vCenter Server. Se si dispone di firewall abilitati, assicurarsi che i firewall siano impostati in modo da consentire eccezioni. 
---
= Requisiti delle porte per gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, i tool di ONTAP utilizzano porte designate per consentire la comunicazione tra i suoi componenti, che comprendono i sistemi storage e VMware vCenter Server. Se si dispone di firewall abilitati, assicurarsi che i firewall siano impostati in modo da consentire eccezioni.

Per i firewall diversi da Windows, è necessario concedere manualmente l'accesso a porte specifiche utilizzate dagli strumenti ONTAP. Se non si concede l'accesso a queste porte, viene visualizzato un messaggio di errore simile al seguente.

`Unable to communicate with the server.`

Gli strumenti ONTAP utilizzano le seguenti porte TCP bidirezionali predefinite:

|===


| *Numero di porta predefinito* | *Descrizione* 


 a| 
9083
 a| 
Quando questa opzione è attivata, il provider VASA e l'adattatore di replica dello storage (SRA) utilizzano questa porta per comunicare con il server vCenter. Questa porta è necessaria anche per ottenere le impostazioni TCP/IP. Questa porta viene utilizzata per scaricare il pacchetto di supporto VP, accedere all'interfaccia utente Web-CLI e controllare la comunicazione del percorso da VMware a VP.



 a| 
443
 a| 
A seconda di come sono state configurate le credenziali, VMware vCenter Server e i sistemi storage sono in attesa di comunicazioni sicure su questa porta. La porta viene utilizzata nell'architettura di comunicazione client-server. La porta 443 è attivata per impostazione predefinita per le connessioni sicure. Il client, che può essere qualsiasi client di automazione che utilizza l'API REST, avvia la connessione al server e gli endpoint si scambiano i dati.



 a| 
8143
 a| 
Gli strumenti ONTAP sono in ascolto per comunicazioni sicure su questa porta. La porta viene utilizzata nell'architettura di comunicazione client-server. Il client, che può essere qualsiasi client di automazione che utilizza l'API REST, avvia la connessione al server e gli endpoint si scambiano i dati. Questa porta è abilitata per i servizi di ONTAP Tools e per l'esportazione dei registri del server di ONTAP Tools. La pagina register.html è ospitata su questa porta. Il RESTO della swap è esposto su questa porta.

|===

NOTE: Prima di implementare gli strumenti ONTAP, è necessario aver attivato il protocollo ICMP (Internet Control message Protocol).

Se ICMP è disattivato, la configurazione iniziale degli strumenti ONTAP non riesce e gli strumenti ONTAP non possono avviare gli strumenti ONTAP e i servizi del provider VASA dopo la distribuzione. Devi abilitare manualmente i tool ONTAP e i servizi del provider VASA dopo l'implementazione.
