---
permalink: deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: Virtual Storage Console, Storage Replication Adapter 
summary: È possibile eseguire un aggiornamento in-place alla versione più recente dei tool ONTAP dalla configurazione esistente della versione 9.10 o successiva seguendo le istruzioni fornite qui. 
---
= Effettua l'aggiornamento alla versione più recente dei tool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire un aggiornamento in-place alla versione più recente dei tool ONTAP dalla versione 9.10 o successiva, seguendo le istruzioni fornite qui.

*Cosa ti serve*

Lo strumento matrice di interoperabilità (IMT) contiene le informazioni più recenti sulle versioni supportate di ONTAP, vCenter Server, host ESXi, applicazioni plug-in e Gestione ripristino sito (SRM). Per https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità"^] informazioni sul percorso di aggiornamento supportato, consultare la sezione.

* È necessario aver scaricato il file _.iso_ per la versione più recente dei tool ONTAP.
* È necessario aver riservato almeno 12 GB di RAM affinché gli strumenti ONTAP funzionino in modo ottimale dopo l'aggiornamento.
* È necessario pulire la cache del browser del client vSphere.
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["Cancellare i pacchetti di plug-in scaricati dalla cache di vSphere"]



Se necessario, attenersi alla seguente procedura per validare il file _.iso_. Questo è un passaggio facoltativo:

. Estrarre la chiave pubblica dal certificato di firma del codice emesso da Entrust (OTV_ISO_CERT.pem) openssl x509 -in OTV_ISO_CERT.pem -pubkey -noout > csc-prod-OTV-SRA-TGZ.pub
. Verificare la firma nel digest utilizzando la chiave pubblica (questo passaggio dovrebbe avvenire nel sistema dell'utente finale prima di installare il file binario. Il bundle di certificati deve essere incluso nel pacchetto di implementazione)
+
openssl dgst -sha256 -verify csc-prod-OTV-SRA-TGZ.pub -Signature netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade-iso.sig netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade.iso



Lo stato del provider VASA dall'implementazione esistente viene mantenuto dopo l'aggiornamento. Dopo l'aggiornamento, attivare o disattivare manualmente il provider VASA in base alle proprie esigenze. Tuttavia, è meglio abilitare il provider VASA anche se i volumi virtuali VMware (vVol) non sono in uso, in quanto abilita i profili di funzionalità dello storage per il provisioning tradizionale del datastore e gli allarmi dello storage.


NOTE: È possibile eseguire un aggiornamento in-place alla versione più recente dei tool ONTAP solo dalla versione 9.10 o successiva.


NOTE: Dall'aggiornamento di ONTAP Tools 9,12, tutti i processi di autenticazione e comunicazione dei sistemi di archiviazione vengono modificati dall'autenticazione di base all'autenticazione basata su certificati mediante l'attendibilità automatica dei certificati di archiviazione ONTAP. Non è richiesta alcuna azione da parte dell'utente.

L'aggiunta di un sistema storage senza autenticazione del certificato è limitata.

Se il sistema storage viene aggiunto con un utente con ambito del cluster creato personalizzato utilizzando il file json e si desidera eseguire l'upgrade alla versione 9,12 e successive
Eseguire i comandi riportati di seguito sulla CLI di ONTAP prima di eseguire l'aggiornamento per abilitare la comunicazione basata su certificato tra gli strumenti ONTAP per VMware vSphere e ONTAP.

. _security login role create -role <existing-role-name> -cmddirname "security login show" -access all_
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all_
. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all_


Se il sistema storage viene aggiunto con un utente SVM scoped creato personalizzato utilizzando il file json e vuoi eseguire l'upgrade a 9,12 e versioni successive, Esegui quindi i seguenti comandi sull'interfaccia a riga di comando di ONTAP con accesso come amministratore del cluster prima dell'aggiornamento per abilitare la comunicazione basata su certificato tra gli strumenti ONTAP per VMware vSphere e ONTAP:

. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all -vserver <vserver-name>_
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application http -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_
. _security login create -user-or-group-name <user> -application ontapi -authentication-method cert -role <existing-role-name> -vserver <vserver-name>_


*Fasi*

. Montare il file _.iso_ scaricato negli strumenti ONTAP:
+
.. Fare clic su *Edit Settings* (Modifica impostazioni) > *DVD/CD-ROM Drive* (unità DVD/CD-ROM).
.. Selezionare *Datastore ISO* file dall'elenco a discesa.
.. Individuare e selezionare il file _.iso_ scaricato, quindi selezionare la casella di controllo *Connetti all'accensione*.


. Accedere alla scheda Riepilogo dei tool ONTAP implementati.
. Avviare la console di manutenzione.
. Al prompt "`Main Menu`", immettere l'opzione `2` Per *Configurazione di sistema*, quindi immettere l'opzione `8` Per *Upgrade*.
+
Al termine dell'aggiornamento, gli strumenti di ONTAP vengono riavviata. Gli strumenti ONTAP sono registrati nel server vCenter con lo stesso indirizzo IP di prima dell'aggiornamento.

. Se si desidera che gli strumenti ONTAP siano registrati con il server vCenter con l'indirizzo IPv6, è necessario eseguire le seguenti operazioni:
+
.. Annullare la registrazione degli strumenti ONTAP.
.. Registrare l'indirizzo IPv6 degli strumenti ONTAP su vCenter Server utilizzando la pagina *Registra*.
.. Rigenera i tool ONTAP per i certificati di VMware vSphere e VASA Provider dopo la registrazione.


+

IMPORTANT: IPv6 è supportato solo con vCenter Server 6.7 e versioni successive.

. Disconnettersi e accedere nuovamente al client vSphere per visualizzare i tool ONTAP implementati.
+
.. Disconnettersi dal client Web vSphere o dal client vSphere esistente e chiudere la finestra.
.. Accedere al client vSphere.
+
L'aggiornamento del plug-in nel client vSphere potrebbe richiedere alcuni minuti.





[NOTE]
====
* A partire dagli strumenti ONTAP per VMware vSphere 9,12, l'autenticazione con ONTAP viene eseguita tramite certificato. È possibile aggiungere un certificato CA firmato o un certificato autofirmato. Vedere, link:../configure/task_modify_storage_system.html["Modificare i sistemi storage"] per istruzioni.
* Se si esegue l'aggiornamento dalla versione 7.0 di ONTAP Tools alla versione più recente di ONTAP Tools, è necessario creare prima profili di capacità di storage prima di tentare di modificare un criterio di storage VM esistente, altrimenti potrebbe verificarsi un errore che indica valori errati o mancanti.
* Se si esegue l'aggiornamento da una versione precedente alla versione più recente dei tool ONTAP, si scopre che il `vvol.rebalance.threshold` proprietà mancante nel file `vvol.properties.
+
Il valore predefinito della proprietà è impostato su 85%.* dopo aver eseguito l'aggiornamento alla versione più recente degli strumenti ONTAP con FIPS abilitato, ma si dispone di una versione precedente di vCenter in cui FIPS non è supportato, la distribuzione continuerà a funzionare.
Tuttavia, se si aggiorna vCenter alla versione più recente supportata da FIPS e si dispone di una versione precedente dei tool ONTAP, l'implementazione funzionerà solo se FIPS è disattivato su vCenter.



====