---
permalink: protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html 
sidebar: sidebar 
keywords: Migration 
summary: 'Se si utilizza Site Recovery Manager basato su Windows (SRM) per il disaster recovery e si desidera utilizzare l"appliance SRM per la stessa configurazione, eseguire la migrazione della configurazione di disaster recovery di Windows all"SRM basato sull"appliance.' 
---
= Migrazione di Windows SRM all'appliance SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza Site Recovery Manager (SRM) basato su Windows per il disaster recovery e si desidera utilizzare SRM Appliance per la stessa configurazione, eseguire la migrazione della configurazione di disaster recovery di Windows all'SRM basato sull'appliance.

Le fasi della migrazione del disaster recovery sono:

. Aggiorna i tool ONTAP esistenti per l'appliance VMware vSphere alla versione più recente.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["Effettua l'aggiornamento alla versione più recente dei tool ONTAP"]

. Migrazione di Storage Replication Adapter basato su Windows a un SRA basato su appliance.
. Migrare i dati di Windows SRM all'appliance SRM.


Vedere https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Installazione e configurazione di Site Recovery Manager"] per i passi dettagliati
