---
permalink: protect/configure_sra_with_srm_shared_site.html 
sidebar: sidebar 
keywords: SRA with SRM 
summary: I tool ONTAP per VMware vSphere supportano la configurazione del sito di recovery condiviso di VMware SRM. 
---
= Configurare SRA con SRM in una configurazione del sito di ripristino condiviso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli strumenti ONTAP per VMware vSphere supportano la configurazione del sito di ripristino condiviso SRM di VMware. Per ulteriori informazioni, vedere:  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/site-recovery-manager/8-8/site-recovery-manager-installation-and-configuration-8-8.html["Site Recovery Manager nella configurazione di un sito di ripristino condiviso"]. Le istanze di Site Recovery Manager Server sul sito di ripristino si connettono alle stesse istanze di vCenter Server.

In una configurazione del sito di ripristino condiviso SRM, ogni server SRM deve disporre di un'istanza SRA dedicata (relazione 1:1 tra SRM e SRA). Configurare OTV in modalità VCF per agire come istanza SRA dedicata per ciascun server SRM. Puoi anche disporre di tool ONTAP non abilitati per SRA per l'appliance VMware vSphere, registrati con vCenter e utilizzati per task non-SRA come il provisioning dei datastore.

Il https://kb.netapp.com/mgmt/OTV/SRA/Storage_Replication_Adapter%3A_How_to_configure_SRA_in_a_SRM_Shared_Recovery_Site["Come configurare SRA in un sito di ripristino condiviso SRM"] L'articolo della Knowledge base descrive in dettaglio la procedura per impostare SRA per supportare la configurazione del sito di ripristino condiviso SRM.
