---
permalink: protect/task_configure_storage_replication_adapter_for_san_environment.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario configurare i sistemi storage prima di eseguire Storage Replication Adapter (SRA) per Site Recovery Manager (SRM).' 
---
= Configurare Storage Replication Adapter per l'ambiente SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare i sistemi storage prima di eseguire Storage Replication Adapter (SRA) per Site Recovery Manager (SRM).

*Cosa ti serve*

È necessario aver installato i seguenti programmi sul sito protetto e sul sito di ripristino:

* SRM
+
La documentazione sull'installazione di SRM è disponibile sul sito VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentazione di VMware Site Recovery Manager"]

* SRA
+
L'adattatore viene installato su SRM.



*Fasi*

. Verificare che gli host ESXi primari siano connessi alle LUN nel sistema di storage primario sul sito protetto.
. Verificare che i LUN si trovino in igroups che dispongono di `ostype` Opzione impostata su _VMware_ sul sistema di storage primario.
. Verificare che gli host ESXi del sito di ripristino dispongano della connettività FC o iSCSI appropriata per la macchina virtuale di storage (SVM). Gli host ESXi del sito secondario devono avere accesso allo storage del sito secondario, analogamente gli host ESXi del sito primario devono avere accesso allo storage del sito primario.
+
È possibile eseguire questa operazione verificando che gli host ESXi dispongano di LUN locali collegati alla SVM o utilizzando `fcp show initiators` o il `iscsi show initiators` Sulle SVM. Controllare l'accesso LUN per i LUN mappati in ESXi per verificare la connettività FC e iSCSI.





== Configurare Storage Replication Adapter per l'ambiente NAS

*Cosa ti serve*

È necessario aver installato i seguenti programmi sul sito protetto e sul sito di ripristino:

* SRM
+
La documentazione sull'installazione di SRM è disponibile sul sito VMware.

+
https://www.vmware.com/support/pubs/srm_pubs.html["Documentazione di VMware Site Recovery Manager"]

* SRA
+
L'adattatore viene installato su SRM e sul server SRA.



*Fasi*

. Verificare che gli archivi dati del sito protetto contengano macchine virtuali registrate con vCenter Server.
. Verificare che gli host ESXi nel sito protetto abbiano montato i volumi di esportazione NFS dalla macchina virtuale di storage (SVM).
. Verificare che gli indirizzi validi come l'indirizzo IP, il nome host o l'FQDN su cui sono presenti le esportazioni NFS siano specificati nel campo *NFS Addresses* (indirizzi NFS) quando si utilizza la procedura guidata Array Manager per aggiungere array a SRM.
. Utilizzare `ping` Su ciascun host ESXi nel sito di ripristino per verificare che l'host disponga di una porta VMkernel in grado di accedere agli indirizzi IP utilizzati per le esportazioni NFS dalla SVM.


https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"]
