---
permalink: protect/task_protect_non_protected_virtual_machines.html 
sidebar: sidebar 
keywords: virtual machines, configuring protection 
summary: È possibile configurare la protezione per le macchine virtuali non protette create utilizzando la policy di storage delle macchine virtuali con la replica disattivata. Per garantire la protezione, è necessario modificare il criterio di storage delle macchine virtuali e assegnare un gruppo di replica. 
---
= Proteggere le macchine virtuali non protette
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare la protezione per le macchine virtuali non protette create utilizzando la policy di storage delle macchine virtuali con la replica disattivata. Per garantire la protezione, è necessario modificare il criterio di storage delle macchine virtuali e assegnare un gruppo di replica.

*A proposito di questa attività*

Se SVM dispone di LIF IPv4 e IPv6, è necessario disattivare le LIF IPv6 e successivamente eseguire i flussi di lavoro di disaster recovery.

*Fasi*

. Fare clic sulla macchina virtuale richiesta e verificare che sia configurata con il criterio di storage della macchina virtuale predefinito.
. Fare clic con il pulsante destro del mouse sulla macchina virtuale selezionata, quindi fare clic su *VM Policies* > *Edit VM Storage Policies* (Criteri di storage delle macchine virtuali).
. Selezionare un criterio di storage delle macchine virtuali per il quale è stata attivata la replica dall'elenco a discesa *criterio di storage delle macchine virtuali*.
. Selezionare un gruppo di replica dall'elenco a discesa *Replication group*, quindi fare clic su *OK*.
. Verificare il Riepilogo della macchina virtuale per confermare che la macchina virtuale è protetta.
+
[NOTE]
====
** Questa release di strumenti ONTAP non supporta la clonazione a caldo di macchine virtuali protette. Spegnere la macchina virtuale ed eseguire l'operazione di clonazione.
** Se un datastore non viene visualizzato negli strumenti di ONTAP dopo un'operazione di protezione, è necessario eseguire una ricerca del sistema di storage o attendere la successiva operazione di rilevamento pianificata.


====

