---
permalink: protect/task_verify_the_replicated_storage_environment.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver configurato Storage Replication Adapter (SRA), è necessario verificare che il sito protetto e il sito di ripristino siano associati correttamente. Il sistema di storage replicato deve essere rilevabile sia dal sito protetto che dal sito di ripristino.' 
---
= Verificare i sistemi storage replicati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato Storage Replication Adapter (SRA), è necessario verificare che il sito protetto e il sito di ripristino siano associati correttamente. Il sistema di storage replicato deve essere rilevabile sia dal sito protetto che dal sito di ripristino.

*Cosa ti serve*

* È necessario aver configurato il sistema storage.
* È necessario associare il sito protetto e il sito di ripristino utilizzando SRM Array Manager.
* Prima di eseguire il test delle operazioni di failover e failover per SRA, è necessario aver abilitato la licenza FlexClone e la licenza SnapMirror.


*Fasi*

. Accedere al server vCenter.
. Accedere a *Site Recovery* > *Array Based Replication*.
. Selezionare la SVM richiesta, quindi verificare i dettagli corrispondenti nelle coppie di array.
+
I sistemi storage devono essere rilevati nel sito protetto e nel sito di ripristino con lo stato "`Enabled`".


