---
permalink: protect/task_update_sra_credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Affinché SRM comunichi con SRA, è necessario aggiornare le credenziali SRA sul server SRM se sono state modificate. 
---
= Aggiornare le credenziali SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Affinché SRM comunichi con SRA, è necessario aggiornare le credenziali SRA sul server SRM se sono state modificate.

È necessario eliminare la cartella macchina SRM nella cache ONTAP Tools username password e reinstallare SRA.

*Cosa ti serve*

Dovresti aver eseguito i passaggi descritti nell'argomento link:../protect/task_configure_sra_on_srm_appliance.html["Configurazione di SRA sull'appliance SRM"]

*Fasi*

. Eseguire i seguenti comandi per eliminare la cartella macchina SRM memorizzata nella cache ONTAP Tools username password:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`


. Eseguire il comando perl per configurare SRA con le nuove credenziali:
+
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. È necessario disporre di un'unica citazione relativa al valore della password.
+
Viene visualizzato un messaggio di conferma dell'avvenuta memorizzazione delle credenziali di storage. SRA può comunicare con il server SRA utilizzando l'indirizzo IP, la porta e le credenziali forniti.




