---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP supportano una configurazione ad alta disponibilità per fornire funzionalità ininterrotte degli strumenti ONTAP durante i guasti. 
---
= Configurare l'alta disponibilità per gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli strumenti ONTAP supportano una configurazione ad alta disponibilità (ha) per fornire funzionalità ininterrotte degli strumenti ONTAP durante i guasti.

I tool ONTAP si affidano alla funzionalità di alta disponibilità (ha) di VMware vSphere e alla funzionalità di fault tolerance (FT) di vSphere per garantire un'elevata disponibilità. La soluzione ad alta disponibilità (ha) offre un rapido ripristino in caso di interruzioni causate da:

* Errore host
* Errore di rete
* Errore della macchina virtuale (errore del sistema operativo guest)
* Arresto anomalo dell'applicazione (strumenti ONTAP)


Non è richiesta alcuna configurazione aggiuntiva per gli strumenti ONTAP per garantire l'alta disponibilità. Solo gli host vCenter Server e ESXi devono essere configurati con la funzionalità VMware vSphere ha o vSphere FT in base ai requisiti. Sia ha che FT richiedono host in cluster insieme allo storage condiviso. FT presenta requisiti e limitazioni aggiuntivi.

Oltre alla soluzione VMware vSphere ha e alla soluzione vSphere FT, i tool ONTAP consentono anche di mantenere costantemente in esecuzione i servizi degli strumenti ONTAP. Il processo di controllo degli strumenti ONTAP monitora periodicamente tutti e tre i servizi e li riavvia automaticamente quando viene rilevato un qualsiasi tipo di errore. In questo modo si evitano gli errori delle applicazioni.


NOTE: VCenter ha non è supportato dai tool ONTAP.



== VMware vSphere ha

È possibile configurare l'ambiente vSphere in cui vengono implementati gli strumenti ONTAP per VMware vSphere per l'alta disponibilità (ha). La funzionalità VMware ha offre protezione di failover da guasti hardware e guasti del sistema operativo negli ambienti virtuali.

La funzione VMware ha monitora le macchine virtuali per rilevare guasti al sistema operativo e all'hardware. Quando viene rilevato un errore, la funzione VMware ha riavvia le macchine virtuali sugli altri server fisici nel pool di risorse. L'intervento manuale non è necessario quando viene rilevato un guasto al server.

La procedura di configurazione di VMware ha dipende dalla versione di vCenter Server in uso. Ad esempio, è possibile utilizzare il seguente collegamento di riferimento e selezionare la versione di vCenter Server richiesta per visualizzare la procedura di configurazione di VMware ha.

https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-availability/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["Documentazione VMware vSphere: Creazione e utilizzo di cluster ha vSphere"]



== Tolleranza agli errori di VMware vSphere

La funzione Fault Tolerance (FT) di VMware vSphere offre un'elevata disponibilità (ha) a un livello superiore e consente di proteggere le macchine virtuali senza alcuna perdita di dati o connessioni. È necessario attivare o disattivare gli strumenti vSphere FT per ONTAP dal server vCenter.

Assicurati che la licenza vSphere supporti FT con il numero di vCPU necessarie per gli strumenti ONTAP nel tuo ambiente (almeno 2 vCPU; 4 vCPU per ambienti su larga scala).

VSphere FT consente alle macchine virtuali di funzionare in modo continuo anche in caso di guasti al server. Quando vSphere FT è attivato su una macchina virtuale, viene creata automaticamente una copia della macchina virtuale primaria su un altro host (la macchina virtuale secondaria) selezionato da Distributed Resource Scheduler (DRS). Se DRS non è attivato, l'host di destinazione viene selezionato tra gli host disponibili. VSphere FT gestisce la macchina virtuale primaria e la macchina virtuale secondaria in modalità lockstep, con ogni mirroring dello stato di esecuzione della macchina virtuale primaria sulla macchina virtuale secondaria.

Quando si verifica un guasto hardware che causa il guasto della macchina virtuale primaria, la macchina virtuale secondaria rileva immediatamente il punto in cui si è arrestata la macchina virtuale primaria. La macchina virtuale secondaria continua a funzionare senza alcuna perdita di connessioni di rete, transazioni o dati.

Il sistema deve soddisfare i requisiti della CPU, i requisiti dei limiti delle macchine virtuali e i requisiti di licenza per la configurazione di vSphere FT per l'istanza di vCenter Server.

La procedura per configurare ha dipende dalla versione di vCenter Server. Ad esempio, è possibile utilizzare il seguente collegamento di riferimento e selezionare la versione di vCenter Server richiesta per visualizzare la procedura di configurazione di ha.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["Documentazione di VMware vSphere: Requisiti di tolleranza agli errori, limiti e licenze"]
