---
permalink: concepts/concept_privileges_required_for_vsc_tasks.html 
sidebar: sidebar 
keywords:  
summary: I diversi strumenti ONTAP per le attività di VMware vSphere richiedono diverse combinazioni di privilegi specifici per i tool ONTAP e i privilegi vCenter Server nativi. 
---
= Privilegi richiesti per le attività degli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I diversi strumenti ONTAP per le attività di VMware vSphere richiedono diverse combinazioni di privilegi specifici per i tool ONTAP e i privilegi vCenter Server nativi.

Informazioni sui privilegi richiesti per le attività degli strumenti ONTAP sono disponibili nell'articolo 1032542 della Knowledge base di NetApp.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Virtual_Storage_Console_for_VMware_vSphere/How_to_configure_RBAC_for_Virtual_Storage_Console["Come configurare RBAC per Virtual Storage Console"]



== Privilegio a livello di prodotto richiesto dai tool ONTAP per VMware vSphere

Per accedere ai tool ONTAP per l'interfaccia grafica di VMware vSphere, è necessario disporre del privilegio di visualizzazione specifico per gli strumenti ONTAP a livello di prodotto, assegnato al livello di oggetto vSphere corretto. Se si effettua l'accesso senza questo privilegio, quando si fa clic sull'icona NetApp, ONTAP Tools visualizza un messaggio di errore e impedisce l'accesso agli strumenti ONTAP.

Con il privilegio *Visualizza*, è possibile accedere alla GUI degli strumenti di ONTAP. Questo privilegio non consente di eseguire attività all'interno degli strumenti ONTAP. Per eseguire qualsiasi attività relativa agli strumenti ONTAP, è necessario disporre dei privilegi vCenter Server nativi e specifici per gli strumenti ONTAP appropriati per tali attività.

Il livello di assegnazione determina le parti dell'interfaccia utente che è possibile visualizzare. L'assegnazione del privilegio View all'oggetto root (cartella) consente di accedere agli strumenti ONTAP facendo clic sull'icona NetApp.

È possibile assegnare il privilegio View a un altro livello di oggetti vSphere; tuttavia, ciò limita i menu degli strumenti ONTAP che è possibile visualizzare e utilizzare.

L'oggetto root è la posizione consigliata per assegnare qualsiasi autorizzazione contenente il privilegio View.
