---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Per semplificare l"utilizzo dei privilegi di vCenter Server e del controllo degli accessi basato sui ruoli, i tool ONTAP forniscono ruoli standard degli strumenti ONTAP che consentono di eseguire attività chiave degli strumenti ONTAP. Esiste anche un ruolo di sola lettura che consente di visualizzare le informazioni, ma non di eseguire attività.' 
---
= Ruoli standard forniti con gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per semplificare l'utilizzo dei privilegi di vCenter Server e del RBAC (role-based access control), gli strumenti ONTAP forniscono ruoli standard di ONTAP Tools che consentono di eseguire le attività chiave degli strumenti ONTAP. Esiste anche un ruolo di sola lettura che consente di visualizzare le informazioni, ma non di eseguire attività.

I ruoli standard dei tool ONTAP dispongono sia dei privilegi specifici dei tool ONTAP che dei privilegi nativi del server vCenter necessari agli utenti per eseguire le attività dei tool ONTAP. Inoltre, i ruoli sono configurati in modo da disporre dei privilegi richiesti per tutte le versioni supportate di vCenter Server.

In qualità di amministratore, è possibile assegnare questi ruoli agli utenti in base alle esigenze.


NOTE: Quando si aggiornano gli strumenti ONTAP alla versione più recente, i ruoli standard vengono automaticamente aggiornati per funzionare con la nuova versione dello strumento.

È possibile visualizzare i ruoli standard degli strumenti ONTAP facendo clic su *ruoli* nella home page del client vSphere.

I ruoli forniti dagli strumenti ONTAP consentono di eseguire le seguenti attività:

|===


| *Ruolo* | *Descrizione* 


 a| 
Amministratore di VSC
 a| 
Fornisce tutti i privilegi nativi di vCenter Server e i privilegi specifici degli strumenti ONTAP necessari per eseguire tutte le attività degli strumenti ONTAP.



 a| 
VSC di sola lettura
 a| 
Fornisce accesso in sola lettura agli strumenti ONTAP. Questi utenti non possono eseguire alcuna azione di ONTAP Tools controllata dall'accesso.



 a| 
Provisioning VSC
 a| 
Fornisce tutti i privilegi nativi di vCenter Server e i privilegi specifici dei tool ONTAP necessari per eseguire il provisioning dello storage. È possibile eseguire le seguenti operazioni:

* Creare nuovi datastore
* Distruggere i datastore
* Visualizza informazioni sui profili delle funzionalità di storage


|===


== Linee guida per l'utilizzo dei ruoli standard degli strumenti ONTAP

Quando si lavora con gli strumenti ONTAP standard per i ruoli di VMware vSphere, è necessario seguire alcune linee guida.

Non modificare direttamente i ruoli standard. In tal caso, gli strumenti ONTAP sovrascriveranno le modifiche ogni volta che si esegue l'aggiornamento. Il programma di installazione aggiorna le definizioni dei ruoli standard ogni volta che si aggiornano gli strumenti ONTAP. In questo modo si garantisce che i ruoli siano aggiornati per la versione degli strumenti ONTAP e per tutte le versioni supportate di vCenter Server.

Tuttavia, è possibile utilizzare i ruoli standard per creare ruoli personalizzati in base all'ambiente. A tale scopo, è necessario copiare il ruolo standard degli strumenti ONTAP e quindi modificare il ruolo copiato. Creando un nuovo ruolo, è possibile mantenere questo ruolo anche quando si riavvia o si aggiorna il servizio Windows di ONTAP Tools.

Di seguito sono riportati alcuni dei modi in cui è possibile utilizzare i ruoli standard degli strumenti ONTAP:

* Utilizzare i ruoli standard degli strumenti ONTAP per tutte le attività degli strumenti ONTAP.
+
In questo scenario, i ruoli standard forniscono tutti i privilegi di cui un utente ha bisogno per eseguire le attività degli strumenti ONTAP.

* Combina i ruoli per espandere le attività che un utente può eseguire.
+
Se i ruoli standard degli strumenti ONTAP forniscono una granularità eccessiva per l'ambiente, è possibile espandere i ruoli creando gruppi di livello superiore che contengono più ruoli.

+
Se un utente deve eseguire altre attività di strumenti non ONTAP che richiedono ulteriori privilegi nativi di vCenter Server, è possibile creare un ruolo che fornisca tali privilegi e aggiungerlo anche al gruppo.

* Crea ruoli più specifici.
+
Se l'azienda richiede l'implementazione di ruoli più restrittivi rispetto ai ruoli standard degli strumenti ONTAP, è possibile utilizzare i ruoli degli strumenti ONTAP per creare nuovi ruoli.

+
In questo caso, clonare i ruoli degli strumenti ONTAP necessari e modificare il ruolo clonato in modo che disponga solo dei privilegi richiesti dall'utente.


