---
permalink: concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'VCenter Server offre un controllo degli accessi basato sui ruoli che consente di controllare l"accesso agli oggetti vSphere. Nei tool ONTAP® per VMware vSphere, vCenter Server RBAC lavora con ONTAP RBAC per determinare quali attività VSC un utente specifico può eseguire sugli oggetti di un sistema storage specifico.' 
---
= Panoramica del controllo degli accessi basato sui ruoli negli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCenter Server offre RBAC (role-based access control) che consente di controllare l'accesso agli oggetti vSphere. Nei tool ONTAP® per VMware vSphere, vCenter Server RBAC lavora con ONTAP RBAC per determinare quali attività VSC un utente specifico può eseguire sugli oggetti di un sistema storage specifico.

Per completare correttamente un'attività, è necessario disporre delle autorizzazioni RBAC vCenter Server appropriate. Durante un'attività, VSC controlla le autorizzazioni vCenter Server di un utente prima di controllare i privilegi ONTAP dell'utente.

È possibile impostare le autorizzazioni vCenter Server sull'oggetto root (nota anche come cartella root). È quindi possibile perfezionare la protezione limitando le entità figlio che non necessitano di tali autorizzazioni.
