---
permalink: concepts/reference_metrocluster_configurations_supported_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP per VMware vSphere supportano ambienti che utilizzano configurazioni MetroCluster IP e FC per ONTAP. La maggior parte di questo supporto è automatica. Tuttavia, potrebbero verificarsi alcune differenze quando si utilizza un ambiente MetroCluster con VSC e provider VASA. 
---
= Configurazioni MetroCluster supportate dai tool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per VMware vSphere supportano ambienti che utilizzano configurazioni MetroCluster IP e FC per ONTAP. La maggior parte di questo supporto è automatica. Tuttavia, potrebbero verificarsi alcune differenze quando si utilizza un ambiente MetroCluster con VSC e provider VASA.


NOTE: SRA non supporta le configurazioni MetroCluster.



== Configurazioni MetroCluster e VSC

È necessario assicurarsi che VSC rilevi i controller del sistema di storage nel sito primario e nel sito secondario. In genere, VSC rileva automaticamente i controller dello storage. Se si utilizza una LIF di gestione del cluster, è consigliabile verificare che VSC abbia rilevato i cluster in entrambi i siti. In caso contrario, è possibile aggiungere manualmente i controller di storage a VSC. È inoltre possibile modificare le coppie di nome utente e password utilizzate da VSC per connettersi ai controller di storage.

Quando si verifica uno switchover, le SVM sul sito secondario prendono il controllo. Questi SVM hanno il suffisso "`-mc`" aggiunto ai loro nomi. Se si verifica un'operazione di switchover mentre si eseguono operazioni come il provisioning di un datastore, il nome della SVM in cui risiede il datastore viene modificato in modo da includere il suffisso "`-mc`". Questo suffisso viene eliminato quando si verifica lo switchback e le SVM sul sito primario riprendono il controllo.


NOTE: Se sono state aggiunte delle SVM dirette con configurazione MetroCluster a VSC, dopo lo switchover, la modifica nel nome della SVM (l'aggiunta del suffisso "`-mc`") non viene riflessa. Tutte le altre operazioni di switchover continuano a essere eseguite normalmente.

Quando si verifica uno switchover o uno switchback, VSC potrebbe impiegare alcuni minuti per rilevare e rilevare automaticamente i cluster. Se ciò accade durante un'operazione VSC, ad esempio il provisioning di un datastore, potrebbe verificarsi un ritardo.



== Configurazioni MetroCluster e provider VASA

Il provider VASA supporta automaticamente gli ambienti che utilizzano configurazioni MetroCluster. Lo switchover è trasparente negli ambienti provider VASA. Non è possibile aggiungere SVM dirette al provider VASA.


NOTE: IL provider VASA non aggiunge il suffisso "`-mc`" ai nomi delle SVM sul sito secondario dopo uno switchover.
