---
permalink: concepts/reference_product_level_privilege_required_by_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'Per accedere ai tool ONTAP® per l"interfaccia grafica di VMware vSphere, è necessario disporre del privilegio di visualizzazione specifico di VSC a livello di prodotto assegnato al livello di oggetto vSphere corretto. Se si effettua l"accesso senza questo privilegio, VSC visualizza un messaggio di errore quando si fa clic sull"icona NetApp e impedisce l"accesso a VSC.' 
---
= Privilegio a livello di prodotto richiesto dai tool ONTAP per VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per accedere ai tool ONTAP® per l'interfaccia grafica di VMware vSphere, è necessario disporre del privilegio di visualizzazione specifico di VSC a livello di prodotto assegnato al livello di oggetto vSphere corretto. Se si effettua l'accesso senza questo privilegio, VSC visualizza un messaggio di errore quando si fa clic sull'icona NetApp e impedisce l'accesso a VSC. Con il privilegio *View*, è possibile accedere alla GUI VSC. Questo privilegio non consente di eseguire attività all'interno di VSC. Per eseguire qualsiasi attività VSC, è necessario disporre dei privilegi vCenter Server nativi e specifici di VSC corretti per tali attività.

Il livello di assegnazione determina le parti dell'interfaccia utente che è possibile visualizzare. L'assegnazione del privilegio View all'oggetto root (cartella) consente di accedere a VSC facendo clic sull'icona NetApp.

È possibile assegnare il privilegio View a un altro livello di oggetto vSphere; tuttavia, ciò limita i menu VSC che è possibile visualizzare e utilizzare.

L'oggetto root è la posizione consigliata per assegnare qualsiasi autorizzazione contenente il privilegio View.
