---
permalink: configure/reference_set_ipv4_or_ipv6.html 
sidebar: sidebar 
keywords:  
summary: È stata aggiunta una nuova opzione al file delle preferenze kaminoprefs.xmlche è possibile impostare per abilitare il supporto per IPv4 o IPv6 per tutti i sistemi di storage aggiunti a VSC. 
---
= Impostare IPv4 o IPv6 utilizzando il file delle preferenze
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I file delle preferenze contengono impostazioni che controllano i tool ONTAP per le operazioni di VMware vSphere. Nella maggior parte dei casi, non è necessario modificare le impostazioni di questi file. È utile conoscere i file delle preferenze utilizzati da Virtual Storage Console (VSC).

VSC dispone di diversi file di preferenze. Questi file includono chiavi di immissione e valori che determinano il modo in cui VSC esegue varie operazioni. Di seguito sono riportati alcuni dei file delle preferenze utilizzati da VSC:

`/opt/netapp/vscserver/etc/kamino/kaminoprefs.xml`

`/opt/netapp/vscserver/etc/vsc/vscPreferences.xml`

In alcune situazioni potrebbe essere necessario modificare i file delle preferenze. Ad esempio, se si utilizza iSCSI o NFS e la subnet è diversa tra gli host ESXi e il sistema di storage, è necessario modificare i file delle preferenze. Se non si modificano le impostazioni nel file delle preferenze, il provisioning del datastore non riesce perché VSC non può montare il datastore.

Al file delle preferenze è stata aggiunta una nuova opzione `kaminoprefs.xml` Che è possibile impostare per abilitare il supporto per IPv4 o IPv6 per tutti i sistemi storage aggiunti a VSC.

* Il `default.override.option.provision.mount.datastore.address.family` il parametro è stato aggiunto a. `kaminoprefs.xml` File delle preferenze per impostare un protocollo LIF dati preferito per il provisioning del datastore.
+
Questa preferenza è applicabile a tutti i sistemi storage aggiunti a VSC.

* I valori per la nuova opzione sono `IPv4`, `IPv6`, e. `NONE`.
* Per impostazione predefinita, il valore è impostato su `NONE`.


|===


| *Valore* | *Descrizione* 


 a| 
NESSUNO
 a| 
* Il provisioning avviene utilizzando lo stesso tipo di indirizzo IPv6 o IPv4 di dati LIF del tipo di cluster o LIF di gestione SVM utilizzato per l'aggiunta dello storage.
* Se lo stesso tipo di indirizzo IPv6 o IPv4 di dati LIF non è presente nella SVM, il provisioning avviene attraverso l'altro tipo di dati LIF, se disponibile.




 a| 
IPv4
 a| 
* Il provisioning avviene utilizzando la LIF dei dati IPv4 nella SVM selezionata.
* Se la SVM non dispone di una LIF di dati IPv4, il provisioning avviene attraverso la LIF di dati IPv6, se disponibile nella SVM.




 a| 
IPv6
 a| 
* Il provisioning avviene utilizzando la LIF dei dati IPv6 nella SVM selezionata.
* Se la SVM non dispone di una LIF dati IPv6, il provisioning avviene attraverso la LIF dati IPv4, se disponibile nella SVM.


|===
Per configurare IPv4 o IPv6 utilizzando l'interfaccia utente, consultare le seguenti sezioni:

* link:../configure/add_different_subnets.html["Aggiungere sottoreti diverse"]
* link:../configure/task_enable_datastore_mounting_across_different_subnets.html["Attiva il montaggio del datastore su diverse subnet"]

