---
permalink: configure/task_create_storage_capability_profiles.html 
sidebar: sidebar 
keywords:  
summary: Puoi utilizzare i tool di ONTAP per creare manualmente profili di funzionalità dello storage, generare automaticamente un profilo in base alle funzionalità di un datastore o modificare un profilo per soddisfare i tuoi requisiti. 
---
= Creazione di profili di funzionalità storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare i tool di ONTAP per creare manualmente profili di funzionalità dello storage, generare automaticamente un profilo in base alle funzionalità di un datastore o modificare un profilo per soddisfare i tuoi requisiti.

*Cosa ti serve*

È necessario aver registrato l'istanza del provider VASA con i tool ONTAP per VMware vSphere.

Dopo aver configurato un profilo, è possibile modificarlo in base alle esigenze.

*Fasi*

. Nella pagina iniziale degli strumenti ONTAP, fare clic su *Criteri e profili*.
. Creare un profilo o modificare un profilo esistente, come richiesto:
+
|===


| *Se si desidera...* | *Eseguire questa operazione...* 


 a| 
Creare un profilo
 a| 
Fare clic su *CREATE* (CREA).



 a| 
Modificare un profilo esistente
 a| 
Fare clic sul profilo che si desidera modificare dai profili elencati nella pagina *Storage Capability Profiles*.

|===
+

NOTE: Per visualizzare i valori associati a un profilo esistente, fare clic sul nome del profilo nella pagina Storage Capabilities Profile. IL provider VASA visualizza quindi la pagina Riepilogo del profilo.

. Da *New Datastore* > *Storage Systems*, fare clic su *Create storage capability profile*.
+
Viene visualizzato il seguente messaggio per confermare la partenza dalla finestra del datastore.

+
_Questa operazione rimuoverà i dati immessi chiudendo il flusso di lavoro corrente e aprirà il workflow Create storage capability profile. Continuare?_

. Fare clic su *YES* per aprire la finestra Create storage capability profile (Crea profilo capacità di storage).
. Completare le pagine della procedura guidata Create Storage Capability Profile per impostare un profilo o modificare i valori per modificare un profilo esistente.
+
La maggior parte dei campi di questa procedura guidata sono esplicativi. La seguente tabella descrive alcuni dei campi per i quali potrebbe essere necessaria una guida.

+
|===


| *Campo* | *Spiegazione* 


 a| 
Identificazione di più profili
 a| 
È possibile utilizzare il campo *Descrizione* nella scheda Nome e Descrizione per descrivere lo scopo del profilo SCP (Storage Capability Profile). Fornire una buona descrizione è utile perché è consigliabile impostare profili diversi in base alle applicazioni in uso.

Ad esempio, un'applicazione business-critical richiede un profilo con funzionalità che supportano performance più elevate, come le piattaforme AFF e ASA. Un datastore utilizzato per il test o il training potrebbe utilizzare un profilo con una piattaforma ibrida Flash Array a performance inferiori e consentire a tutte le funzionalità di efficienza dello storage e il tiering di controllare i costi.
La combinazione di tipo di piattaforma e flag asimmetrico determina il tipo di SCP. Ad esempio: Platinum_ASA_A, Platinum_AFF_A, Platinum_AFF_C.

Se è stata attivata la modalità "`Linked`" per i server vCenter, è necessario selezionare il server vCenter per cui si sta creando il profilo di capacità storage.



 a| 
Piattaforma
 a| 
A partire dai tool ONTAP per VMware vSphere 9,13, puoi creare profili di funzionalità dello storage utilizzando una combinazione dei seguenti elementi:

.. Tipo di piattaforma: Performance, capacità e Flash Array ibridi
.. Indicatore asimmetrico - indica lo stato ottimizzato per SAN (All SAN Array) del sistema storage.
+
*** Quando il tipo di piattaforma è *Performance* e il flag asimmetrico è *TRUE*, prende in considerazione il sistema di storage di tipo AFF-A.
*** Quando il tipo di piattaforma è *Performance* e l'indicatore asimmetrico è *False*, considera il sistema di archiviazione di tipo ASA-A.
*** Quando il tipo di piattaforma è *Capacity* e il flag asimmetrico è *True*, prende in considerazione il sistema di storage di tipo AFF-C.
*** Quando il tipo di piattaforma è *Flash Hybrid array* e il flag asimmetrico è NA, prende in considerazione il sistema storage di tipo FAS




Le opzioni nelle schermate successive vengono aggiornate in base alla selezione del tipo di sistema di storage.



 a| 
Protocollo
 a| 
È possibile selezionare uno dei protocolli disponibili elencati in base alla piattaforma selezionata per il sistema di storage. Durante la configurazione delle macchine virtuali, è possibile configurare le policy di storage delle macchine virtuali con il profilo di capacità dello storage e il campo del protocollo filtra i datastore in base a un protocollo specifico. Il campo 'Any' consente di lavorare con tutti i protocolli.



 a| 
Performance
 a| 
È possibile impostare le policy QoS tradizionali per il sistema storage utilizzando la scheda Performance (prestazioni).

** Quando si seleziona *None* (Nessuno), viene applicata una policy QoS senza limiti (infinito) a un volume dati.
** Quando si seleziona *QoS Policy Group*, viene applicata una policy QoS tradizionale a un volume.
+
È possibile impostare il valore per *IOPS max* e *IOPS min* che consentono di utilizzare la funzionalità QoS. Se si seleziona Infinite IOPS, il campo Max IOPS viene disattivato. Quando viene applicata a un datastore tradizionale, viene creata una policy di QoS con il valore "`MAX IOPS`" e assegnata a un volume FlexVol. Se utilizzato con un datastore vVol, viene creata una policy QoS con valori IOPS max e IOPS min per ogni datastore vVol di dati.

+
*NOTA*:

+
*** È possibile applicare al volume FlexVol anche i valori massimi di IOPS e minimo IOPS per un datastore tradizionale.
*** È necessario assicurarsi che le metriche delle performance non siano impostate separatamente a livello di storage virtual machine (SVM), aggregato o volume FlexVol.






 a| 
Attributi dello storage
 a| 
Gli attributi di storage che è possibile attivare in questa scheda dipendono dal tipo di storage selezionato nella scheda Personality.

** Se selezioni lo storage ibrido Flash Array, puoi configurare la riserva di spazio (thick o thin) e abilitare la deduplica, la compressione e la crittografia.
+
L'attributo di tiering è disattivato perché questo attributo non è applicabile allo storage ibrido Flash Array.

** Se si seleziona lo storage AFF, è possibile attivare la crittografia e il tiering.
+
Deduplica e compressione sono attivate per impostazione predefinita per lo storage AFF e non possono essere disattivate.

** Se scegli lo storage ASA, puoi abilitare crittografia e tiering.
+
La deduplica e la compressione sono abilitate per impostazione predefinita per lo storage ASA e non possono essere disabilitate.

+
L'attributo tiering consente l'utilizzo di volumi che fanno parte di un aggregato abilitato a FabricPool (supportato dal provider VASA per sistemi AFF con ONTAP 9.4 e versioni successive). È possibile configurare uno dei seguenti criteri per l'attributo tiering:

** None (Nessuno): Impedisce lo spostamento dei dati del volume nel Tier di capacità
** Snapshot: Sposta i blocchi di dati utente delle copie Snapshot del volume non associate al file system attivo nel Tier di capacità


|===
. Rivedere le selezioni nella pagina Summary (Riepilogo), quindi fare clic su *OK*.
+
Dopo aver creato un profilo, è possibile tornare alla pagina Storage Mapping (mappatura dello storage) per visualizzare i profili corrispondenti agli archivi dati.


