---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile eseguire il provisioning di un datastore vVol utilizzando la procedura guidata Provision Datastore (Provision Datastore) solo se il provider VASA è attivato negli strumenti ONTAP.' 
---
= Provisioning degli archivi dati vVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il provisioning di un datastore vVol utilizzando la procedura guidata Provision Datastore (Provision Datastore) solo se il provider VASA è attivato negli strumenti ONTAP.

*Cosa ti serve*

* Assicurarsi che i dettagli della subnet di tutte le reti a cui è connesso ESXi siano inseriti nel file Kaminoprefs.xml.
+
Vedere la sezione *abilitazione del montaggio del datastore su diverse subnet*.

* È necessario configurare criteri di replica simili e pianificare gli archivi dati nei siti di origine e di destinazione per eseguire correttamente la replica inversa.


Il menu del datastore di provisioning consente di specificare un profilo di capacità dello storage per il datastore, che consente di specificare obiettivi di livello di servizio (SLO) coerenti e di semplificare il processo di provisioning. È possibile specificare un profilo di capacità di storage solo se è stato attivato il provider VASA.

I volumi FlexVol utilizzati come storage di backup vengono visualizzati nella dashboard di vVol solo se eseguono ONTAP 9.5 o versioni successive. Non utilizzare la procedura guidata vCenter Server New Datastore per eseguire il provisioning degli archivi dati vVols.

* È necessario utilizzare le credenziali del cluster per creare datastore vVols.
+
Non è possibile utilizzare le credenziali SVM per creare datastore vVols.

* IL provider VASA non supporta la clonazione di una macchina virtuale ospitata nel datastore vVols di un protocollo in un altro datastore con un protocollo diverso.
* È necessario aver completato l'associazione dei cluster e l'associazione SVM sia sui siti di origine che di destinazione.


*A proposito di questa attività*


NOTE: La versione 9.10 dei tool ONTAP supporta la creazione di datastore vVol con dimensioni vmdk superiori a 16 TB per tutte le piattaforme di storage ONTAP 9.9.1 o successive DI tipo SAN Array (ASA).

*Fasi*

. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center su cui si desidera eseguire il provisioning del datastore.
. Specificare gli host su cui si desidera montare l'archivio dati.
+
|===


| *Per rendere disponibile il datastore a...* | *Eseguire questa operazione...* 


 a| 
Tutti gli host di un data center
 a| 
Fare clic con il pulsante destro del mouse su un data center, quindi selezionare *NetApp ONTAP Tools* > *Provision Datastore*.



 a| 
Tutti gli host di un cluster
 a| 
Fare clic con il pulsante destro del mouse su un cluster, quindi selezionare *NetApp ONTAP Tools* > *Provision Datastore*.



 a| 
Un singolo host
 a| 
Fare clic con il pulsante destro del mouse su un host, quindi selezionare *NetApp ONTAP Tools* > *Provision Datastore*.

|===
. Completare i campi nella finestra di dialogo nuovo archivio dati per creare l'archivio dati.
+
La maggior parte dei campi della finestra di dialogo sono esplicativi. La seguente tabella descrive alcuni dei campi per i quali potrebbe essere necessaria una guida.

+
|===


| *Sezione* | *Descrizione* 


 a| 
Generale
 a| 
La sezione General (Generale) della finestra di dialogo New Datastore (nuovo archivio dati) fornisce le opzioni per inserire la posizione, il nome, la descrizione, il tipo e il protocollo per il nuovo archivio dati. Il tipo di datastore vVols viene utilizzato per configurare un datastore vVols.

È possibile eseguire il provisioning del datastore vVols se la funzionalità del provider VASA è attivata. Vedere, link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html["Abilitare il provider VASA per la configurazione di datastore virtuali"] per ulteriori informazioni. Il datastore vVols supporta i protocolli NFS, iSCSI, FC/FEoE e NVMe/FC.


NOTE: Il protocollo NVMe/FC per il datastore vVol è disponibile se gli strumenti ONTAP sono registrati con vCenter 8.0 e versioni successive e se la versione di ONTAP è ONTAP 9.91P3 e versioni successive.


NOTE: Se si esegue il provisioning del datastore vVols iSCSI per la replica vVols, prima di creare il datastore vVols nel sito di destinazione, è necessario eseguire l'aggiornamento SnapMirror e il riscoperta del cluster.



 a| 
Sistema storage
 a| 
Questa sezione consente di selezionare se si desidera attivare o disattivare la replica nel datastore vVols. Per questa release è consentito solo il profilo di replica di tipo asincrono. È quindi possibile selezionare uno o più profili di capacità storage elencati. I valori consigliati dal sistema di *Storage System* e *Storage VM* associati vengono popolati automaticamente. I valori consigliati vengono popolati solo se associati in ONTAP. Se necessario, è possibile modificare questi valori.

*Nota:* durante la creazione di volumi FlexVol in ONTAP, è necessario assicurarsi di crearli con gli attributi che si desidera selezionare nel profilo delle funzionalità di storage. Sia i volumi FlexVol di protezione dei dati che di lettura/scrittura devono avere attributi simili.

Una volta creati i volumi FlexVol e inizializzato SnapMirror in ONTAP, è necessario eseguire una riscoperta dello storage in VSC per visualizzare i nuovi volumi.



 a| 
Attributi dello storage
 a| 
Selezionare la pianificazione per SnapMirror e il volume FlexVol richiesto dall'elenco esistente. Questa pianificazione deve essere simile a quella selezionata nella pagina delle policy di storage delle macchine virtuali. L'utente dovrebbe aver creato i volumi FlexVol su ONTAP con SnapMirror elencati. È possibile selezionare il profilo di capacità storage predefinito da utilizzare per la creazione di vVol utilizzando l'opzione *Default storage capability profile*. Per impostazione predefinita, tutti i volumi sono impostati sulla dimensione massima di crescita automatica al 120% e le istantanee predefinite sono attivate su questi volumi.

*Nota:*

** Un volume FlexVol che fa parte di un datastore vVol non può ridursi al di sotto delle dimensioni esistenti ma può crescere del 120% al massimo. Gli snapshot predefiniti sono attivati su questo volume FlexVol.
** La dimensione minima del volume FlexVol da creare è di 5 GB.


|===
. Nella sezione Summary (Riepilogo), fare clic su *Finish* (fine).


*Risultato*

Un gruppo di replica viene creato nel backend quando viene configurato un datastore vVols.

*Informazioni correlate*

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["Analizza i dati delle performance utilizzando la dashboard di vVols"]
