---
permalink: configure/task_discover_storage_systems_and_hosts.html 
sidebar: sidebar 
keywords:  
summary: Quando si eseguono per la prima volta i tool ONTAP in un client vSphere, i tool ONTAP rilevano gli host ESXi, le LUN e le esportazioni NFS e i sistemi storage NetApp che gestiscono tali LUN ed esportazioni. 
---
= Rilevamento di host e sistemi storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si eseguono per la prima volta i tool ONTAP in un client vSphere, i tool ONTAP rilevano gli host ESXi, le LUN e le esportazioni NFS e i sistemi storage NetApp che gestiscono tali LUN ed esportazioni.

*Cosa ti serve*

* Tutti gli host ESXi devono essere accesi e connessi.
* Tutte le macchine virtuali di storage (SVM) da rilevare devono essere in esecuzione e ciascun nodo del cluster deve avere almeno una LIF di dati configurata per il protocollo di storage in uso (NFS, iSCSI, FC o NVMe/FC).


*A proposito di questa attività*

È possibile scoprire nuovi sistemi storage o aggiornare le informazioni sui sistemi storage esistenti per ottenere le informazioni più aggiornate sulla capacità e sulla configurazione in qualsiasi momento. Puoi anche modificare le credenziali utilizzate dai tool di ONTAP per accedere ai sistemi storage.

Durante il rilevamento dei sistemi storage, i tool ONTAP raccolgono informazioni dagli host ESXi gestiti dall'istanza di vCenter Server.

*Fasi*

. Dalla home page del client vSphere, selezionare *host e cluster*.
. Fare clic con il pulsante destro del mouse sul data center desiderato, quindi selezionare *NetApp ONTAP Tools* > *Aggiorna dati host e storage* .
+
Gli strumenti di ONTAP visualizzano una finestra di dialogo di conferma che informa che questa azione riavvierà il rilevamento di tutti i sistemi di archiviazione connessi e potrebbe richiedere alcuni minuti. Continuare?

. Fare clic su *sì*.
. Selezionare i controller di storage rilevati con lo stato `Authentication Failure`, Quindi fare clic su *AZIONI* > *Modifica*.
. Inserire le informazioni richieste nella finestra di dialogo *Modify Storage System* (Modifica sistema di storage).
. Ripetere i passaggi 4 e 5 per tutti i controller storage con `Authentication Failure` stato.


Al termine del processo di rilevamento, eseguire le seguenti operazioni:

* Utilizzare gli strumenti ONTAP per configurare le impostazioni dell'host ESXi per gli host che visualizzano l'icona Avviso nella colonna Impostazioni scheda, nella colonna Impostazioni MPIO o nella colonna Impostazioni NFS.
* Fornire le credenziali del sistema storage.

