---
permalink: configure/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: È possibile utilizzare i tool ONTAP® per VMware vSphere per impostare le credenziali predefinite per un sistema storage nel server vCenter. 
---
= Impostare le credenziali predefinite per i sistemi storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare gli strumenti ONTAP per VMware vSphere per impostare le credenziali predefinite per un sistema storage nel server vCenter.

*Cosa ti serve*

È necessario selezionare il vCenter Server che si desidera utilizzare per creare le credenziali predefinite.

*A proposito di questa attività*

Se si configurano credenziali predefinite per i sistemi storage, i tool ONTAP utilizzano queste credenziali per accedere a un sistema storage appena rilevato dai tool ONTAP. Se le credenziali predefinite non funzionano, è necessario accedere manualmente al sistema di storage. I tool ONTAP e SRA supportano l'aggiunta di credenziali del sistema storage a livello di cluster o di SVM. Tuttavia, il provider VASA funziona solo con le credenziali a livello di cluster.

*Fasi*

. Nella pagina iniziale degli strumenti ONTAP, fare clic su *Impostazioni* > *Impostazioni amministrative* > *Configura credenziali predefinite per il sistema di storage*.
. Nella finestra di dialogo Storage System Default Credentials (credenziali predefinite del sistema di storage), immettere il nome utente e la password per il sistema di storage.
+
Le credenziali dello storage controller vengono assegnate in ONTAP in base alla coppia di nome utente e password. Le credenziali dello storage controller possono essere l'account amministratore o un account personalizzato che utilizza RBAC (role-based access control).

+
Non è possibile utilizzare gli strumenti di ONTAP per modificare i ruoli associati alla coppia di nome utente e password dello storage controller. Per modificare o creare un nuovo ruolo utente ONTAP da utilizzare con gli strumenti ONTAP, è possibile utilizzare Gestione sistema.

+
Vedere link:..configure/task_configure_user_role_and_privileges.html["Configurare i ruoli e i privilegi degli utenti"]sezione.

. Fare clic su *OK* per salvare le credenziali predefinite.


Se le credenziali del sistema di storage sono state aggiornate perché è stato segnalato un sistema di storage `Authentication Failure` Fare clic sull'opzione *RISCOPRI TUTTO* disponibile nella pagina dei sistemi storage. Durante questa operazione, gli strumenti di ONTAP tentano di connettersi al sistema di storage utilizzando le nuove credenziali.
