---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile raccogliere i file di log per i tool ONTAP® per VMware vSphere dall"opzione disponibile nell"interfaccia grafica utente di VSC. Il supporto tecnico potrebbe richiedere di raccogliere i file di registro per risolvere un problema.' 
---
= Raccogliere i file di log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile raccogliere i file di log per gli strumenti ONTAP per VMware vSphere dall'opzione disponibile nell'interfaccia grafica utente (GUI) di VSC. Il supporto tecnico potrebbe richiedere di raccogliere i file di registro per risolvere un problema.

*A proposito di questa attività*

Se sono necessari i file di log del provider VASA, è possibile generare un pacchetto di supporto dalla schermata del pannello di controllo del fornitore. Questa pagina fa parte dei menu di manutenzione del provider VASA, accessibili dalla console dell'appliance virtuale.

`\https://vm_ip:9083`

È possibile raccogliere i tool ONTAP per i file di log di VMware vSphere utilizzando la funzione "`Export ONTAP Tools for VMware vSphere Logs`" (Strumenti di esportazione per i log di VMware vSphere) nell'interfaccia grafica di VSC. Quando si raccoglie un pacchetto di tool ONTAP per VMware vSphere Log con il provider VASA abilitato, il bundle di tool ONTAP per VMware vSphere Log avrà anche i log VP. I seguenti passaggi spiegano come raccogliere i tool ONTAP per i file di log di VMware vSphere:

*Fasi*

. Dalla home page dei tool ONTAP, fare clic su *Configurazione* > *Esporta tool ONTAP per i log VMware vSphere*.
+
Questa operazione può richiedere alcuni minuti.

. Quando richiesto, salvare il file sul computer locale.
+
È quindi possibile inviare il file _.zip_ al supporto tecnico.


