---
permalink: manage/task_mount_datastores_on_host.html 
sidebar: sidebar 
keywords:  
summary: 'Il montaggio di un datastore fornisce l"accesso allo storage a host aggiuntivi. È possibile montare il datastore sugli host aggiuntivi dopo aver aggiunto gli host all"ambiente VMware.' 
---
= Montare il datastore su host aggiuntivi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il montaggio di un datastore fornisce l'accesso allo storage a host aggiuntivi. È possibile montare il datastore sugli host aggiuntivi dopo aver aggiunto gli host all'ambiente VMware.

*Cosa ti serve*

Assicurarsi che i dettagli della subnet di tutte le reti a cui è connesso ESXi host siano inseriti in `Kaminoprefs.xml`.

Vedere la sezione attivazione del montaggio del datastore su diverse subnet.

*Fasi*

. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center che contiene l'host.
. Ripetere il passaggio 2 per tutti gli host aggiuntivi.
. Fare clic con il pulsante destro del mouse sull'host, quindi selezionare *NetApp ONTAP Tools* > *Mount Datastore*.
. Selezionare gli archivi dati che si desidera montare, quindi fare clic su *OK*.

