---
permalink: manage/task_resize_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Il ridimensionamento di un datastore consente di aumentare o diminuire lo storage per i file delle macchine virtuali. Potrebbe essere necessario modificare le dimensioni di un datastore man mano che cambiano i requisiti dell"infrastruttura.' 
---
= Ridimensionare gli archivi dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ridimensionamento di un datastore consente di aumentare o diminuire lo storage per i file delle macchine virtuali. Potrebbe essere necessario modificare le dimensioni di un datastore man mano che cambiano i requisiti dell'infrastruttura.

*A proposito di questa attività*

Se si desidera che VSC ridimensioni il volume contenente quando ridimensiona il datastore VMFS, non utilizzare l'opzione *Use existing volume* (Usa volume esistente) nella sezione Storage Attributes (attributi di storage) durante il provisioning iniziale del datastore VMFS, ma lasciare che crei automaticamente un nuovo volume per ciascun datastore.

È possibile aumentare o ridurre le dimensioni di un datastore NFS, ma per un datastore VMFS è possibile solo aumentarle. Il ridimensionamento del datastore è supportato anche per gli archivi dati FlexGroup con opzione di crescita e riduzione automatica. Un FlexGroup che fa parte di un datastore tradizionale e di un volume FlexVol che fa parte di un datastore vVols non può ridursi al di sotto delle dimensioni esistenti ma può crescere al massimo del 120%. Gli snapshot predefiniti sono attivati su questi volumi FlexGroup e FlexVol.


NOTE: Se si utilizzano piattaforme di storage di tipo All SAN Array (ASA) con ONTAP 9.9.1 o versione successiva, solo allora è possibile creare datastore vVol con dimensioni vmdk superiori a 16 TB.

*Fasi*

. Dalla home page del client vSphere, fare clic su *host e cluster*.
. Nel riquadro di navigazione, selezionare il data center che contiene il datastore.
. Fare clic con il pulsante destro del mouse sull'archivio dati e selezionare *NetApp ONTAP Tools* > *Assegna QoS*.
. Nella finestra di dialogo Ridimensiona, specificare una nuova dimensione per l'archivio dati, quindi fare clic su *OK*.
+
È possibile eseguire l'opzione *RISCOPRI TUTTO* nel menu Storage Systems (sistemi storage) per aggiornare manualmente l'elenco di storage in Storage Systems and Dashboard (sistemi storage e dashboard) o attendere il successivo aggiornamento pianificato.


