---
permalink: manage/task_collect_the_log_files.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile raccogliere i file di registro per gli strumenti ONTAP® per VMware vSphere dall"opzione disponibile nell"interfaccia utente grafica \(GUI\) degli strumenti ONTAP. Il supporto tecnico potrebbe richiedere di raccogliere i file di registro per risolvere un problema.' 
---
= Raccogliere i file di log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi raccogliere i file di log per i tool ONTAP per VMware vSphere dall'opzione disponibile nell'interfaccia grafica (GUI) dei tool ONTAP. Il supporto tecnico potrebbe richiedere di raccogliere i file di registro per risolvere un problema.

*A proposito di questa attività*

Se sono necessari i file di log del provider VASA, è possibile generare un pacchetto di supporto dalla schermata del pannello di controllo del fornitore. Questa pagina fa parte dei menu di manutenzione del provider VASA, accessibili dalla console dell'appliance virtuale.

`\https://vm_ip:9083`

È possibile raccogliere gli strumenti ONTAP per i file di log di VMware vSphere utilizzando la funzione "`Esporta strumenti ONTAP per i log di VMware vSphere'" nella GUI degli strumenti di ONTAP. Quando si raccoglie un pacchetto di tool ONTAP per VMware vSphere Log con il provider VASA abilitato, il bundle di tool ONTAP per VMware vSphere Log avrà anche i log VP. I seguenti passaggi spiegano come raccogliere i tool ONTAP per i file di log di VMware vSphere:

*Fasi*

. Dalla home page dei tool ONTAP, fare clic su *Configurazione* > *Esporta tool ONTAP per i log VMware vSphere*.
+
Questa operazione può richiedere alcuni minuti.

. Quando richiesto, salvare il file sul computer locale.
+
È quindi possibile inviare il file _.zip_ al supporto tecnico.


