---
permalink: manage/task_change_the_administrative_password.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile modificare la password di amministratore degli strumenti ONTAP dopo l"implementazione utilizzando la console di manutenzione.' 
---
= Modificare la password dell'amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password di amministratore degli strumenti ONTAP dopo l'implementazione utilizzando la console di manutenzione. La password scade dopo 90 giorni.


NOTE: Dopo aver modificato la password di amministratore nella console di manutenzione di ONTAP Tools, se SRA è attivato e configurato negli strumenti ONTAP, eseguire la procedura *aggiornamento credenziali SRA* descritta in link:../qsg.html["Tool ONTAP per la guida rapida di VMware vSphere"] sezione. Il mancato rispetto di queste istruzioni causa errori riportati su SRM.

*Fasi*

. Dal server vCenter, aprire una console per accedere agli strumenti di ONTAP.
. Accedere come utente di manutenzione.
. Invio `1` Nella console di manutenzione per selezionare Application Configuration (Configurazione applicazione).
. Invio `6` Per selezionare *Modifica password utente 'amministratore'*.
. Immettere una password di almeno otto caratteri e un massimo di 30 caratteri. La password deve contenere almeno un carattere superiore, un carattere inferiore, un carattere e un carattere speciale. L'avviso di scadenza della password viene visualizzato dopo 75 giorni dalla reimpostazione della password. La nuova password non può essere uguale all'ultima password utilizzata.
+
Se non si seguono le raccomandazioni relative alla password, l'opzione della console di manutenzione è limitata alla modifica della password. Una volta scaduta la password, viene richiesto di modificarla.

. Invio `y` nella finestra di dialogo di conferma.

